### ISSUE TITLE
Why Varnish is disabled by default on local?

### ISSUE THREAD

**Issue by Leksat** [amazeeio/drupal-example#42]
https://github.com/amazeeio/drupal-example/blob/d4705750de8c583b5b620bb79e964ddb352f8d02/docker-compose.yml#L123

It took me some time to find why Varnish does not work locally. Even if this was mentioned in the [Lagoon docs](https://lagoon.readthedocs.io/en/latest/using_lagoon/drupal/services/varnish/#test-varnish-locally).

IMHO:
- by default, local settings should be as much close to production settings
- to bypass Varnish we can
  - use route of the `nginx` container
  - use `docker-compose.override.yml` like this:
```
version: '2.3'

services:
  drupal-varnish:
    environment:
      VARNISH_BYPASS: "true"
```

But am I missing something? Is there a reason for having Varnish disabled by default?
